version: '3'

services:
  postgres:
    image: 'postgres:16.2'
    environment:
      POSTGRES_DB: homie
      POSTGRES_USER: postgres # Default
      POSTGRES_HOST_AUTH_METHOD: trust # No PW required
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  worker:
    image: docker:27.1.1-cli
    build:
      context: .
      dockerfile: worker.Dockerfile
    container_name: homie_worker
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis:6379
      POSTGRES_HOST: postgres
    ports:
      - '3100:3100'
